# Generated by Django 4.2.3 on 2023-08-01 19:31

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(upload_to=main.models.generate_unique_filename),
        ),
    ]
